name: Node App Example CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-run-tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]

    outputs:
      result: ${{ steps.jest-test.outputs.test_result }}

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: Install dependencies
      run: npm ci
    - name: Run jest test
      id: jest-test
      run: |
        if npm test ; then
          echo "Test passed"
          echo "test_result=success" >> "$GITHUB_OUTPUT"
        else
          echo "Test failed"
          echo "test_result=failed" >> "$GITHUB_OUTPUT"
        fi



  deploy-to-aws:
    runs-on: ubuntu-latest
    needs: build-and-run-tests
    if: ${{ needs.build-and-run-tests.outputs.result == 'success' }}

    steps:
    - name: Deploy
      run: echo "Deploying..."
